name: supabase_notes
version: 1.0.0+1
publish_to: none
description: CRUD with Authentication and Authorization using GET X CLI and Supabase.
environment:
  sdk: ">=2.18.5 <3.10.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  supabase_flutter: ^2.8.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  enum_to_string: ^2.2.0
  icon_font_generator: ^4.0.0
  expandable_widgets: ^1.0.3+1
  fanci: ^1.2.1
  extended_tabs: ^4.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
  uses-material-design: true

  fonts:
    - family: "UIcons"
      fonts:
        - asset: "fonts/uicon.otf"

icon_font:
  input_svg_dir: "assets/uicons-bold-straight/svg"
  output_font_file: "fonts/uicon.otf"

  output_class_file: "lib/uicon.dart"
  class_name: "UIcons"
  format: true

  font_name: "UIcons"
  normalize: true
  ignore_shapes: false

  recursive: true
  verbose: false